### PR TITLE
Updating Deps

### PR DESCRIPTION
**Pull request by Aderinom**
Heyo VMTran! 

I've found your library after starting to implement a nestJs adapter for uws with a different express wrapper. Seeing as this implementation of yours seems very clean I want to start using that.

As such I'd like to start by updating the productive dependencies!

### CODE REVIEW

**Comment by waghanza** [comment]
The https://github.com/uNetworking/uWebSockets.js version is not compatible with the latest `node` **LTS** (18.14)

cc @vmtrandev

**Comment by Aderinom** [comment]
> The https://github.com/uNetworking/uWebSockets.js version is not compatible with the latest `node` **LTS** (18.14)
> 
> cc @vmtrandev

~~Where did you find this information?~~
~~According to a previous release note they plan to support three LTS versions.~~ ~~Currently 18, 16 and 14~~

~~https://github.com/uNetworking/uWebSockets.js/releases/tag/v20.7.0~~

Was confused, now I understand you meant the old v18.14.0 ver of UWS.Js

**Comment by vmtrandev** [comment]
@Aderinom Thanks for your contribution. I've been developing the version 2 of this library for a while which is lighter, well-organized, better adapter support for NestJS. The v2 is currently being used privately but I will release it shortly in March. Your PR will be also merged and released asap provided that the CI/CD pipeline is still working.

**Comment by Aderinom** [comment]
Looking forward to seeing version 2 😄

**Pull request merged**
